# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]

trigger:
- master

pool:
  vmImage: 'Ubuntu-latest'

stages:
- stage: build
  jobs:
    - job: build
      steps:
      - checkout: self
        persistCredentials: true
        clean: true

      - script: npm install
        displayName: 'npm install'

      - script: npm run build
        displayName: 'run build'

      - script: npm run test
        displayName: 'run test'
